# Generated by Django 3.2.7 on 2021-10-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit_prize',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
