# Generated by Django 3.2.7 on 2021-10-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_inventory_unit_prize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=60, null=True)),
                ('patient_age', models.IntegerField(null=True)),
                ('birth_date', models.DateTimeField(max_length=50, null=True)),
                ('patient_contact', models.CharField(max_length=50, null=True)),
                ('civil_status', models.CharField(max_length=20, null=True)),
                ('patient_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('patient_address', models.CharField(max_length=100, null=True)),
                ('patient_occupation', models.CharField(max_length=50, null=True)),
                ('patient_company_name', models.CharField(max_length=50, null=True)),
                ('patient_complaint', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(max_length=50, null=True)),
                ('patient_name', models.CharField(max_length=50, null=True)),
                ('doctor_name', models.CharField(max_length=50, null=True)),
                ('payment_date', models.DateTimeField(max_length=50, null=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('installment', 'Installment'), ('check', 'Check'), ('online', 'Online')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=20, null=True)),
                ('fee', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='contact',
        ),
        migrations.AddField(
            model_name='inventory',
            name='company_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_prize',
            field=models.FloatField(null=True),
        ),
    ]
