# Generated by Django 3.2.7 on 2021-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20211015_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accoutn_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('staff', 'Staff')], max_length=50, null=True),
        ),
    ]
