# Generated by Django 3.2.7 on 2021-10-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='treatment',
        ),
        migrations.AddField(
            model_name='department',
            name='treatment',
            field=models.ManyToManyField(to='management.Treatment'),
        ),
    ]
