# Generated by Django 3.2.7 on 2021-10-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20211015_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='treatment',
            new_name='treatments',
        ),
    ]
