# Generated by Django 3.2.7 on 2021-10-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_treatment_department_treatments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='treatments',
            new_name='treatment',
        ),
    ]
