# Generated by Django 3.2.7 on 2021-10-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20211015_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_schedule',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
