# Generated by Django 3.2.7 on 2021-10-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_rename_patient_contact_doctor_doctor_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='username',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
