# Generated by Django 3.2.7 on 2021-10-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_patienthistory_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
