# Generated by Django 3.2.7 on 2021-10-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accoutn_role',
            new_name='account_role',
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_complaint',
            field=models.TextField(),
        ),
    ]
