# Generated by Django 3.2.7 on 2021-10-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20211018_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_address',
            field=models.TextField(),
        ),
    ]
