# Generated by Django 3.2.7 on 2021-10-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20211020_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_contact',
            new_name='patient_HomePhone',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_Phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='refferedBy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
