# Generated by Django 3.2.7 on 2021-10-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_patient_patient_securityno'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.treatment'),
        ),
    ]
