# Generated by Django 3.2.7 on 2021-10-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_auto_20211022_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_historyothers',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
