# Generated by Django 3.2.7 on 2021-10-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_patient_patient_birthplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='refferedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
