# Generated by Django 3.2.7 on 2021-10-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_alter_patient_refferedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_officeAddress',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_specialty',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_officeAddressDoctor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_specialtyDoctor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_alchohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_allergyOthers',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_devAbnormalities',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_drugs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_historyothers',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_hospitalization',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_lastDentalVisit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_lastTreatmentDone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_medications',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_previousDentist',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_previousDoctor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_tabacco',
            field=models.BooleanField(default=False),
        ),
    ]
