# Generated by Django 3.2.7 on 2021-10-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_auto_20211022_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_birthPlace',
        ),
    ]
