# Generated by Django 3.2.7 on 2021-10-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_patient_patient_whatdrugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_whatDrugs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
