# Generated by Django 3.2.7 on 2021-10-25 08:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_alter_patient_patient_whatdrugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='company_contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
