# Generated by Django 3.2.7 on 2021-10-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_alter_inventory_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_personToCallAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
