# Generated by Django 3.2.7 on 2021-10-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_auto_20211026_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_alchohol',
        ),
    ]
