# Generated by Django 3.2.7 on 2021-10-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_alter_patient_patient_officeaddressdoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
