# Generated by Django 3.2.7 on 2021-11-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_rename_issue_by_inventory_issue_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
