# Generated by Django 3.2.7 on 2021-11-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_alter_account_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTimeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTimeOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='account',
            name='schedule_day',
        ),
        migrations.AddField(
            model_name='account',
            name='schedule_timeIn',
            field=models.ManyToManyField(null=True, to='management.ScheduleTimeIn'),
        ),
        migrations.AddField(
            model_name='account',
            name='schedule_timeOut',
            field=models.ManyToManyField(null=True, to='management.ScheduleTimeOut'),
        ),
        migrations.AddField(
            model_name='account',
            name='schedule_day',
            field=models.ManyToManyField(null=True, to='management.ScheduleDay'),
        ),
    ]
