# Generated by Django 3.2.7 on 2021-11-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_auto_20211103_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletimein',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scheduletimeout',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
