# Generated by Django 3.2.7 on 2021-11-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_auto_20211103_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='schedule_timeIn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='schedule_timeOut',
        ),
        migrations.AddField(
            model_name='account',
            name='schedule_time',
            field=models.TimeField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='account',
            name='schedule_day',
        ),
        migrations.AddField(
            model_name='account',
            name='schedule_day',
            field=models.DateTimeField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], null=True),
        ),
        migrations.DeleteModel(
            name='ScheduleDay',
        ),
        migrations.DeleteModel(
            name='ScheduleTimeIn',
        ),
        migrations.DeleteModel(
            name='ScheduleTimeOut',
        ),
    ]
