# Generated by Django 3.2.7 on 2021-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0055_alter_account_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
