# Generated by Django 3.2.7 on 2021-11-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0057_account_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_picture',
        ),
    ]
