# Generated by Django 3.2.7 on 2021-11-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
