# Generated by Django 3.2.7 on 2021-11-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_auto_20211112_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='full_name',
            new_name='doctor_name',
        ),
    ]
