# Generated by Django 3.2.7 on 2021-11-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0070_auto_20211112_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='doctor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.account'),
        ),
    ]
