# Generated by Django 3.2.7 on 2021-11-16 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_auto_20211112_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='treatment',
        ),
        migrations.AddField(
            model_name='treatment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.department'),
        ),
    ]
