# Generated by Django 3.2.7 on 2021-11-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0076_auto_20211118_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='schedule_day',
        ),
        migrations.AlterField(
            model_name='account',
            name='schedule_time_In',
            field=models.CharField(choices=[('9 AM', '9 am'), ('10 AM', '10 am'), ('11 AM', '11 am'), ('12 PM', '12 pm'), ('1 PM', '1 pm'), ('2 PM', '2 pm'), ('3 PM', '3 pm'), ('4 PM', '4 pm'), ('5 PM', '5 pm')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='schedule_time_Out',
            field=models.CharField(choices=[('9 AM', '9 am'), ('10 AM', '10 am'), ('11 AM', '11 am'), ('12 PM', '12 pm'), ('1 PM', '1 pm'), ('2 PM', '2 pm'), ('3 PM', '3 pm'), ('4 PM', '4 pm'), ('5 PM', '5 pm')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='schedule_day',
            field=models.ManyToManyField(blank=True, null=True, to='management.Day'),
        ),
    ]
