# Generated by Django 3.2.7 on 2021-11-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_auto_20211118_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='schedule_day',
            field=models.ManyToManyField(blank=True, to='management.Day'),
        ),
    ]
