# Generated by Django 3.2.7 on 2021-11-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_alter_account_schedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reorder_level',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
