# Generated by Django 3.2.7 on 2021-11-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_inventory_reorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fee',
            field=models.IntegerField(null=True),
        ),
    ]
