# Generated by Django 3.2.7 on 2021-11-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0080_auto_20211122_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit_prize',
            field=models.IntegerField(null=True),
        ),
    ]
