# Generated by Django 3.2.7 on 2021-11-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0082_alter_payment_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='unit_prize',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
