# Generated by Django 3.2.7 on 2021-11-30 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0085_auto_20211130_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.department'),
        ),
    ]
