# Generated by Django 3.2.7 on 2021-12-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0088_auto_20211203_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_fatherContact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_fatherOfficeContact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_motherContact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_motherOfficeContact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_personToCallPhone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_personToCallWorkTel',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Staff_contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
