# Generated by Django 3.2.7 on 2021-12-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0090_auto_20211203_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_suffixName',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
