# Generated by Django 3.2.7 on 2021-12-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0093_alter_patient_patient_suffixname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='PatientHistory',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
