# Generated by Django 3.2.7 on 2021-12-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0094_auto_20211206_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='issue_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
