# Generated by Django 3.2.7 on 2021-12-07 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0095_inventory_issue_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInventory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('company_contact', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('unit_prize', models.IntegerField(default=0, null=True)),
                ('exp_date', models.DateField(null=True)),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue_to', models.ForeignKey(blank=True, db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.account')),
                ('receive_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.account')),
            ],
            options={
                'verbose_name': 'historical inventory',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
