# Generated by Django 3.2.7 on 2021-12-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0097_historicaldepartment_historicalpatient_historicalpayment_historicaltreatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='tooth_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tooth_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
