# Generated by Django 3.2.7 on 2021-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0099_auto_20211209_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='tooth_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tooth_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
