# Generated by Django 3.2.7 on 2021-12-10 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0100_auto_20211209_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventory',
            name='company_contact',
            field=models.CharField(default=0, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='company_contact',
            field=models.CharField(default=0, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
