# Generated by Django 3.2.7 on 2021-12-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0101_auto_20211210_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('exp_date',)},
        ),
    ]
