# Generated by Django 3.2.7 on 2021-12-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0102_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('product_name',)},
        ),
    ]
