# Generated by Django 3.2.7 on 2021-12-10 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0103_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='patient_lastTreatmentDone',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='patient_nationality',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='patient_occupation',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_lastTreatmentDone',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_nationality',
            field=models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_occupation',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
