# Generated by Django 3.2.7 on 2021-12-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0104_auto_20211210_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='patient_occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_occupation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
