# Generated by Django 3.2.7 on 2021-12-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0106_auto_20211210_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='patient_lastTreatmentDone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='patient_nationality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='patient_religion',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_lastTreatmentDone',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_nationality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_religion',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
