# Generated by Django 3.2.7 on 2021-12-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0107_auto_20211210_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='schedule_time_In',
            field=models.CharField(choices=[('9 am', '9 am'), ('10 am', '10 am'), ('11 am', '11 am'), ('12 am', '12 pm'), ('1 am', '1 pm'), ('2 am', '2 pm'), ('3 am', '3 pm'), ('4 am', '4 pm'), ('5 am', '5 pm')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='schedule_time_Out',
            field=models.CharField(choices=[('9 am', '9 am'), ('10 am', '10 am'), ('11 am', '11 am'), ('12 am', '12 pm'), ('1 am', '1 pm'), ('2 am', '2 pm'), ('3 am', '3 pm'), ('4 am', '4 pm'), ('5 am', '5 pm')], max_length=50, null=True),
        ),
    ]
