# Generated by Django 3.2.7 on 2021-12-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0108_auto_20211216_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='schedule_time_In',
            field=models.CharField(choices=[('9 am', '9 am'), ('10 am', '10 am'), ('11 am', '11 am'), ('12 pm', '12 pm'), ('1 pm', '1 pm'), ('2 pm', '2 pm'), ('3 pm', '3 pm'), ('4 pm', '4 pm'), ('5 pm', '5 pm')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='schedule_time_Out',
            field=models.CharField(choices=[('9 am', '9 am'), ('10 am', '10 am'), ('11 am', '11 am'), ('12 pm', '12 pm'), ('1 pm', '1 pm'), ('2 pm', '2 pm'), ('3 pm', '3 pm'), ('4 pm', '4 pm'), ('5 pm', '5 pm')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='issue_by',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='issue_to',
            field=models.ForeignKey(blank=True, db_constraint=False, default=' ', max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.account'),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='receive_by',
            field=models.ForeignKey(blank=True, db_constraint=False, default=' ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.account'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='issue_by',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='issue_to',
            field=models.ForeignKey(blank=True, default=' ', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='management.account'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='receive_by',
            field=models.ForeignKey(default=' ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='management.account'),
        ),
    ]
