# Generated by Django 3.2.7 on 2021-12-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0109_auto_20211229_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventory',
            name='issue_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='issue_to',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=50, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.account'),
        ),
        migrations.AlterField(
            model_name='historicalinventory',
            name='receive_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='management.account'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='issue_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='issue_to',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='management.account'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='receive_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='management.account'),
        ),
    ]
