# Generated by Django 3.2.7 on 2021-11-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='day',
            new_name='service_required',
        ),
        migrations.RenameField(
            model_name='bookappointment',
            old_name='email',
            new_name='your_date',
        ),
        migrations.RenameField(
            model_name='bookappointment',
            old_name='message',
            new_name='your_email',
        ),
        migrations.RenameField(
            model_name='bookappointment',
            old_name='phone',
            new_name='your_phone',
        ),
        migrations.RenameField(
            model_name='bookappointment',
            old_name='service',
            new_name='your_schedule',
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='time',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='accepted_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='your_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
