# Generated by Django 3.2.7 on 2021-11-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211110_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='apporoved_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='apporoved_time',
            field=models.TimeField(null=True),
        ),
    ]
