# Generated by Django 3.2.7 on 2021-11-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211112_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='apporoved_time',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
