# Generated by Django 3.2.7 on 2021-11-15 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_bookappointment_apporoved_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualConsult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, null=True)),
                ('last_name', models.CharField(max_length=60, null=True)),
                ('phone', models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.CharField(max_length=60, null=True)),
                ('message', models.TextField(blank=True)),
                ('my_message', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
