# Generated by Django 3.2.7 on 2021-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_virtualconsult'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualconsult',
            name='close_up',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='virtualconsult',
            name='full_face',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
