# Generated by Django 3.2.7 on 2021-11-24 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0084_alter_treatment_treatment_fee'),
        ('website', '0006_auto_20211115_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='asign_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.account'),
        ),
    ]
