# Generated by Django 3.2.7 on 2021-11-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_bookappointment_asign_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='asign_doctor',
            new_name='assign_doctor',
        ),
    ]
