# Generated by Django 3.2.7 on 2021-11-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_asign_doctor_bookappointment_assign_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookappointment',
            options={'ordering': ('-accepted_date',)},
        ),
    ]
