# Generated by Django 3.2.7 on 2021-11-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_bookappointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookappointment',
            options={'ordering': ('-accepted_date', '-date_created')},
        ),
    ]
