# Generated by Django 3.2.7 on 2021-11-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0084_alter_treatment_treatment_fee'),
        ('website', '0011_alter_bookappointment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualconsult',
            name='assign_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.account'),
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='assign_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.account'),
        ),
    ]
