# Generated by Django 3.2.7 on 2021-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20211125_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookappointment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualconsult',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
