# Generated by Django 3.2.7 on 2021-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20211126_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualconsult',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
