# Generated by Django 3.2.7 on 2021-11-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_virtualconsult_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
