# Generated by Django 3.2.7 on 2021-11-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookappointment',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='virtualconsult',
            options={'ordering': ('-date_created',)},
        ),
    ]
