# Generated by Django 3.2.7 on 2021-12-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20211130_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='apporoved_date',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
