# Generated by Django 3.2.7 on 2021-12-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_bookappointment_apporoved_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='apporoved_date',
            new_name='approved_date',
        ),
        migrations.RenameField(
            model_name='bookappointment',
            old_name='apporoved_time',
            new_name='approved_time',
        ),
    ]
