# Generated by Django 3.2.7 on 2021-12-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0097_historicaldepartment_historicalpatient_historicalpayment_historicaltreatment'),
        ('website', '0018_auto_20211202_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assign_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.account'),
        ),
        migrations.AddField(
            model_name='contact',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='my_message',
            field=models.TextField(blank=True),
        ),
    ]
