# Generated by Django 3.2.7 on 2021-12-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20211207_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='accepted_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='assign_doctor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_deleted',
        ),
    ]
