# Generated by Django 3.2.7 on 2021-12-16 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_bookappointment_approved_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookappointment',
            options={},
        ),
    ]
