# Generated by Django 3.2.7 on 2021-12-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_bookappointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookappointment',
            options={'ordering': ('-date_created',)},
        ),
    ]
