# Generated by Django 3.2.7 on 2021-12-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_bookappointment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualconsult',
            old_name='is_deleted',
            new_name='done',
        ),
    ]
