# Generated by Django 3.2.7 on 2021-12-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_rename_is_deleted_virtualconsult_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookappointment',
            old_name='is_deleted',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='virtualconsult',
            old_name='done',
            new_name='is_deleted',
        ),
    ]
